using TMPro;
using UnityEngine;
using UnityEngine.UI;
using Sirenix.OdinInspector;

public class AnalyseEnemy : MonoBehaviour
{
    [BoxGroup("Text")]
    [SerializeField]
    private TMP_Text TMPcharacterName;

    [BoxGroup("UI")]
    [SerializeField]
    private Image ImageitemPreview;
    [BoxGroup("UI")]
    [SerializeField]
    private Image healthbar;

    [BoxGroup("Local")]
    [SerializeField]
    private SpriteRenderer ImageitemPreviewOLD;
    [BoxGroup("Local")]
    [SerializeField]
    private SpriteFillBar healthbarOLD;

    [BoxGroup]
    [SerializeField]
    private StatusEffectBar statusEffectBar;

    private AI npc;

    public void Initialize(AI enemy)
    {
        //set type of Analyse
        this.npc = enemy;
    }

    private void LateUpdate()
    {
        showEnemyInfo();
    }

    private void showEnemyInfo()
    {
        if (ImageitemPreview != null) this.ImageitemPreview.gameObject.SetActive(false);
        if (TMPcharacterName != null) this.TMPcharacterName.text = this.npc.GetCharacterName();
        if (healthbar != null) this.healthbar.fillAmount = this.npc.values.life / this.npc.values.maxLife;

        if (ImageitemPreviewOLD != null) this.ImageitemPreviewOLD.gameObject.SetActive(false);
        if (healthbarOLD != null) this.healthbarOLD.fillAmount(this.npc.values.life / this.npc.values.maxLife);

        this.statusEffectBar.setCharacter(this.npc.values);

        if (this.npc.values.itemDrop != null 
         && this.npc.values.currentState != CharacterState.dead
         && this.npc.values.currentState != CharacterState.respawning)
        {
            if (ImageitemPreview != null) this.ImageitemPreview.gameObject.SetActive(true);
            if (ImageitemPreview != null) this.ImageitemPreview.sprite = this.npc.values.itemDrop.stats.getSprite(); //TODONEW

            if (ImageitemPreviewOLD != null) this.ImageitemPreviewOLD.gameObject.SetActive(true);
            if (ImageitemPreviewOLD != null) this.ImageitemPreviewOLD.sprite = this.npc.values.itemDrop.stats.getSprite(); //TODONEW
        }
    }
}
